### ISSUE TITLE
[OPTIONAL]: Text link focus style can be adjusted to background color instead of an outline

### ISSUE THREAD

**Issue by joshkimux** [AIGAdc/dcdesignweek.org-11ty#102]
## Description

Text links are notorious for being tough to do with focus styles when the default is an outline because it can break like this:

<img width="507" alt="Screen Shot 2022-09-23 at 6 22 55 PM" src="https://user-images.githubusercontent.com/14154792/192064469-f5c49492-27ef-4a3f-8106-c504ea1c7d4e.png">

We can get around that by pulling a gov.uk maneuver and using background color instead of outlines for our text links like this:

https://user-images.githubusercontent.com/14154792/192064847-cad4e909-e272-4e4e-afda-932539c12e86.mov

**Comment by joshkimux** [comment]
@silviascript for awareness since this is designy, but optional 😄

**Comment by marcusrelacion** [comment]
@joshkimux added a new label for `2023 DCDW Improvements` where we can define this behavior earlier in the design phase.
