### ISSUE TITLE
Events Hero

### ISSUE THREAD

**Issue by silviascript** [AIGAdc/dcdesignweek.org-11ty#115]
![screenshot](https://netlify-cocoon.netlify.app/.netlify/functions/fetch?code=307&path=eyJzaXRlX2lkIjoiNjk1NmZkOGMtOWNkZS00YmQ1LWE0MTktZjI5ZDY0MGE5OTUyIiwiZGVwbG95X2lkIjoiNjMyZDQ4NDUxOWJiNDEwMDA5NjE4Yzk2IiwiaWQiOiJmMWY2MTk1Mi1jNWVjLTQ2Y2MtODExZC04MDc2M2YwOTdjNjQifQ==)

The header should be 88px instead of 96px but can keep to save time. However, the paragraph is 32px and looks a bit heavy. I'm think we should make all the paragraphs below headers be 24px. Similar to how the homepage is once corrected.

```
Path:      /events/
Browser:   Chrome 105.0.0.0 on Mac OS 10.15.7
Viewport:  1800 x 1013 @2x
Language:  en-US
Cookies:   Enabled
```

[Open in BrowserStack](https://www.browserstack.com/user/try-live?url=https%3A%2F%2Fdeploy-preview-62--2022-dcdw.netlify.app%2Fevents%2F&os=OS%20X&os_version=Catalina&browser=Chrome&browser_version=105.0&resolution=1800x1013&speed=1&start=true&ref=netlify-source)

Submitted from [Netlify Deploy Preview #62](https://deploy-preview-62--2022-dcdw.netlify.app/events/)

**Comment by marcusrelacion** [comment]
Fixed with #107
