### ISSUE TITLE
Filter Styling

### ISSUE THREAD

**Issue by silviascript** [AIGAdc/dcdesignweek.org-11ty#116]
![screenshot](https://netlify-cocoon.netlify.app/.netlify/functions/fetch?code=307&path=eyJzaXRlX2lkIjoiNjk1NmZkOGMtOWNkZS00YmQ1LWE0MTktZjI5ZDY0MGE5OTUyIiwiZGVwbG95X2lkIjoiNjMyZDQ4NDUxOWJiNDEwMDA5NjE4Yzk2IiwiaWQiOiI1NTU4ZjQ1Mi00YTQ5LTQwOWQtOTk4MS0yNzA0Nzg1MzUwNmEifQ==)

The clear filter buttons should be center aligned and button height should be 48px. The filter checkbox should at least be 16px x 16px if we're going in that direction.

Should the title be "Featured Events"? It's really more events that are visible. I would recommend 2022 Events instead since unless Josh has any recommendations.

```
Path:      /events/
Browser:   Chrome 105.0.0.0 on Mac OS 10.15.7
Viewport:  1800 x 1013 @2x
Language:  en-US
Cookies:   Enabled
```

[Open in BrowserStack](https://www.browserstack.com/user/try-live?url=https%3A%2F%2Fdeploy-preview-62--2022-dcdw.netlify.app%2Fevents%2F&os=OS%20X&os_version=Catalina&browser=Chrome&browser_version=105.0&resolution=1800x1013&speed=1&start=true&ref=netlify-source)

Submitted from [Netlify Deploy Preview #62](https://deploy-preview-62--2022-dcdw.netlify.app/events/)

**Comment by marcusrelacion** [comment]
Fixed everything but the size of the checkbox. Will need to apply custom styling and will save that after I fix other bugs.
