### ISSUE TITLE
Events Venue & Preparation

### ISSUE THREAD

**Issue by silviascript** [AIGAdc/dcdesignweek.org-11ty#122]
![screenshot](https://netlify-cocoon.netlify.app/.netlify/functions/fetch?code=307&path=eyJzaXRlX2lkIjoiNjk1NmZkOGMtOWNkZS00YmQ1LWE0MTktZjI5ZDY0MGE5OTUyIiwiZGVwbG95X2lkIjoiNjMyZDQ4NDUxOWJiNDEwMDA5NjE4Yzk2IiwiaWQiOiJkMTRiNjUzMy04ZGZhLTRkMmEtYTBjMS0zMWYxMjYxN2U1YWIifQ==)

The wave between the venue and preparation should have a cream 200 top and cream 100 on the bottom. Only the top parts needs to be corrected. The text should all be the Maroon 200 and not Maroon 100.

The venue text could be right aligned like last year to help find the information quickly.

```
Path:      /event/the-creative's-flow:-yoga-for-release-and-renewal/
Browser:   Chrome 105.0.0.0 on Mac OS 10.15.7
Viewport:  1800 x 1013 @2x
Language:  en-US
Cookies:   Enabled
```

[Open in BrowserStack](https://www.browserstack.com/user/try-live?url=https%3A%2F%2Fdeploy-preview-62--2022-dcdw.netlify.app%2Fevent%2Fthe-creative's-flow%3A-yoga-for-release-and-renewal%2F&os=OS%20X&os_version=Catalina&browser=Chrome&browser_version=105.0&resolution=1800x1013&speed=1&start=true&ref=netlify-source)

Submitted from [Netlify Deploy Preview #62](https://deploy-preview-62--2022-dcdw.netlify.app/event/the-creative's-flow:-yoga-for-release-and-renewal/)

**Comment by marcusrelacion** [comment]
Waves should be updated, but will make a separate issue to move venue to the right in a another push.
