### ISSUE TITLE
Footer Styling

### ISSUE THREAD

**Issue by silviascript** [AIGAdc/dcdesignweek.org-11ty#123]
![screenshot](https://netlify-cocoon.netlify.app/.netlify/functions/fetch?code=307&path=eyJzaXRlX2lkIjoiNjk1NmZkOGMtOWNkZS00YmQ1LWE0MTktZjI5ZDY0MGE5OTUyIiwiZGVwbG95X2lkIjoiNjMyZDQ4NDUxOWJiNDEwMDA5NjE4Yzk2IiwiaWQiOiIwM2JmZGY2Ni1kZTI1LTQyZTUtYjI5ZS1iMWNhZTRkMGVhNmMifQ==)

There should be a wave above the footer section that blends into the cream background. Also, the footer background-color should be Maroon 200 instead of Maroon 100.

```
Path:      /event/the-creative's-flow:-yoga-for-release-and-renewal/
Browser:   Chrome 105.0.0.0 on Mac OS 10.15.7
Viewport:  1800 x 1013 @2x
Language:  en-US
Cookies:   Enabled
```

[Open in BrowserStack](https://www.browserstack.com/user/try-live?url=https%3A%2F%2Fdeploy-preview-62--2022-dcdw.netlify.app%2Fevent%2Fthe-creative's-flow%3A-yoga-for-release-and-renewal%2F&os=OS%20X&os_version=Catalina&browser=Chrome&browser_version=105.0&resolution=1800x1013&speed=1&start=true&ref=netlify-source)

Submitted from [Netlify Deploy Preview #62](https://deploy-preview-62--2022-dcdw.netlify.app/event/the-creative's-flow:-yoga-for-release-and-renewal/)

**Comment by marcusrelacion** [comment]
@silviascript the footer color matches whats in the design, can you clarify if this should be the lighter maroon or the darker one?
