### ISSUE TITLE
City graphic overlays on top of text

### ISSUE THREAD

**Issue by joshkimux** [AIGAdc/dcdesignweek.org-11ty#32]
![screenshot](https://netlify-cocoon.netlify.app/.netlify/functions/fetch?code=307&path=eyJzaXRlX2lkIjoiNjk1NmZkOGMtOWNkZS00YmQ1LWE0MTktZjI5ZDY0MGE5OTUyIiwiZGVwbG95X2lkIjoiNjI5ZGU3MzgxYWQwN2QwMDA4MmI3NDdkIiwiaWQiOiJkZDAxMzdhYS03YzJjLTRkMzMtYjRjNy00YTEzNGZjMTYwOGYifQ==)

### Description of issue
Minor issue, but the city graphic overlaps on top of some of the body paragraph at times making some words more difficult to read.

```
Path:      /accessibility/
Browser:   Chrome 102.0.0.0 on Mac OS 10.15.7
Viewport:  818 x 903 @2x
Language:  en-US
Cookies:   Enabled
```

[Open in BrowserStack](https://www.browserstack.com/user/try-live?url=https%3A%2F%2Fdeploy-preview-19--2022-dcdw.netlify.app%2Faccessibility%2F&os=OS%20X&os_version=Catalina&browser=Chrome&browser_version=102.0&resolution=818x903&speed=1&start=true&ref=netlify-source)

Submitted from [Netlify Deploy Preview #19](https://deploy-preview-19--2022-dcdw.netlify.app/accessibility/)

**Comment by marcusrelacion** [comment]
Fixed
