### ISSUE TITLE
Accordion Arrow Rotation

### ISSUE THREAD

**Issue by silviascript** [AIGAdc/dcdesignweek.org-11ty#40]
![screenshot](https://netlify-cocoon.netlify.app/.netlify/functions/fetch?code=307&path=eyJzaXRlX2lkIjoiNjk1NmZkOGMtOWNkZS00YmQ1LWE0MTktZjI5ZDY0MGE5OTUyIiwiZGVwbG95X2lkIjoiNjI5ZGU3MzgxYWQwN2QwMDA4MmI3NDdkIiwiaWQiOiJjNWE2MmU3ZS00ODdmLTRiZjQtOTgxYS1lNWU4Zjg5ZjZlMDYifQ==)

### Description of issue
The accordions are in different rotations. @marcusrelacion, I can see the way you have it would be better for accessibility purposes. We can change our design to match this. Let me know your thoughts here.

```
Path:      /
Browser:   Chrome 102.0.0.0 on Mac OS 10.15.7
Viewport:  1920 x 1064 @1x
Language:  en-US
Cookies:   Enabled
```

[Open in BrowserStack](https://www.browserstack.com/user/try-live?url=https%3A%2F%2Fdeploy-preview-19--2022-dcdw.netlify.app%2F&os=OS%20X&os_version=Catalina&browser=Chrome&browser_version=102.0&resolution=1920x1064&speed=1&start=true&ref=netlify-source)

Submitted from [Netlify Deploy Preview #19](https://deploy-preview-19--2022-dcdw.netlify.app/)

**Comment by marcusrelacion** [comment]
I would recommend the way it's built on the page since the arrow facing down at least to me would indicate the accordion is active. But I'll defer to what the team thinks we should do.

**Comment by joshkimux** [comment]
@marcusrelacion confirming, but less on accessibility, and more on common UX practice. The arrows (along with the expanded box) are indicating state.
