### ISSUE TITLE
A11y page content changes

### ISSUE THREAD

**Issue by joshkimux** [AIGAdc/dcdesignweek.org-11ty#42]
![screenshot](https://netlify-cocoon.netlify.app/.netlify/functions/fetch?code=307&path=eyJzaXRlX2lkIjoiNjk1NmZkOGMtOWNkZS00YmQ1LWE0MTktZjI5ZDY0MGE5OTUyIiwiZGVwbG95X2lkIjoiNjI5ZGU3MzgxYWQwN2QwMDA4MmI3NDdkIiwiaWQiOiIyY2Y5MWQyNy0xZGViLTRhOWUtYWIxZC0yNjJiM2RhNmUyMTcifQ==)

### Description of issue
The following content should be updated (use ctrl + f to find and replace!)

- Accessibility Commitment
  - Accessibility Statement
- and we are still
  - and that we are still
- List accommodations we can and cannot provide
  - List accommodations we cannot provide
- Provide contacts to request any accommodations that may have been missed or undocumented.
  - Provide contacts to request any accommodations that may be needed
- Encourage feedback from the community on how we can evolve to be more inclusive in the future.
  - Encourage feedback from the community on how we can evolve to be more inclusive by default in the future.
- Complete a Google Sheets accessibility checklist based on Allison Ravenhall’s article Inclusive Design for Accessible Presentations. Attend an inclusive presentation seminar, read an inclusive presentation handout, and review Allison’s article.
  - [Write as a list instead]
  - Complete an accessibility checklist based on Allison Ravenhall's article Inclusive Design for Accessible Presentations
  - Attend an inclusive presentation seminar or review an inclusive presentation handout
- Accommodations that we may be unable to be provided include:
  - Accommodations that we may be unable to provide include
- Need event accommodations?
  - What can you expect?
- We’re providing the following accommodations for our events:
  - We're providing the following accessibility features for our events:
- If you need an accommodation that is unlisted above, please contact us using a method that works
best for you:
  - We recognize that our events are still not completely accessible by default. If you need an accommodation for any of our events, please contact us using a method that works best for you:

The following content should be added:
- List accessibility features we provide at our events [Add as second bullet below "give transparency..."]

```
Path:      /accessibility/
Browser:   Chrome 102.0.0.0 on Mac OS 10.15.7
Viewport:  1053 x 1041 @2x
Language:  en-US
Cookies:   Enabled
```

[Open in BrowserStack](https://www.browserstack.com/user/try-live?url=https%3A%2F%2Fdeploy-preview-19--2022-dcdw.netlify.app%2Faccessibility%2F&os=OS%20X&os_version=Catalina&browser=Chrome&browser_version=102.0&resolution=1053x1041&speed=1&start=true&ref=netlify-source)

Submitted from [Netlify Deploy Preview #19](https://deploy-preview-19--2022-dcdw.netlify.app/accessibility/)

**Comment by marcusrelacion** [comment]
@joshkimux I addressed all these changes minus this one:

"Need event accommodations?
What can you expect?"

I tried to do a find and replace but didn't see the top line, could you verify that's correct?

**Comment by joshkimux** [comment]
On the website it's written as "Event Accommodations" which is a smidge different than the figma!
