### ISSUE TITLE
Header Text Color

### ISSUE THREAD

**Issue by silviascript** [AIGAdc/dcdesignweek.org-11ty#46]
![screenshot](https://netlify-cocoon.netlify.app/.netlify/functions/fetch?code=307&path=eyJzaXRlX2lkIjoiNjk1NmZkOGMtOWNkZS00YmQ1LWE0MTktZjI5ZDY0MGE5OTUyIiwiZGVwbG95X2lkIjoiNjI5ZTg4NWY4MzA3NzQwMDA4MWIwZDYwIiwiaWQiOiI0Mjc2OTQzOC1iNWFlLTQxNWMtOTM4Zi1hZTgwOWNiNTcxZDUifQ==)

### Description of issue
The text should technically be blue but the black works well. Can we change the hero header and description on the homepage to be black as well?

```
Path:      /accessibility/
Browser:   Chrome 102.0.0.0 on Mac OS 10.15.7
Viewport:  1920 x 1064 @1x
Language:  en-US
Cookies:   Enabled
```

[Open in BrowserStack](https://www.browserstack.com/user/try-live?url=https%3A%2F%2Fdeploy-preview-19--2022-dcdw.netlify.app%2Faccessibility%2F&os=OS%20X&os_version=Catalina&browser=Chrome&browser_version=102.0&resolution=1920x1064&speed=1&start=true&ref=netlify-source)

Submitted from [Netlify Deploy Preview #19](https://deploy-preview-19--2022-dcdw.netlify.app/accessibility/)

**Comment by marcusrelacion** [comment]
Fixed. This was an error in the color combo used, will be blue on the next deploy.
