### ISSUE TITLE
Update Description

### ISSUE THREAD

**Issue by silviascript** [AIGAdc/dcdesignweek.org-11ty#56]
![screenshot](https://netlify-cocoon.netlify.app/.netlify/functions/fetch?code=307&path=eyJzaXRlX2lkIjoiNjk1NmZkOGMtOWNkZS00YmQ1LWE0MTktZjI5ZDY0MGE5OTUyIiwiZGVwbG95X2lkIjoiNjJhZTAzNzAyZDFkMTIwMDA5NWM5ZDNmIiwiaWQiOiJhNmFjNDI3MS1jNTE5LTQ5M2QtYjY1Yi0xOTkxYmY0NDI2ZmQifQ==)

### Description of issue
The volunteer card is taller than the sponsorship card. Let's update the beginning text of the volunteer card to "We'll need help ..." to help with the card height.

```
Path:      /
Browser:   Chrome 102.0.0.0 on Mac OS 10.15.7
Viewport:  1800 x 1014 @2x
Language:  en-US
Cookies:   Enabled
```

[Open in BrowserStack](https://www.browserstack.com/user/try-live?url=https%3A%2F%2Fdeploy-preview-54--2022-dcdw.netlify.app%2F&os=OS%20X&os_version=Catalina&browser=Chrome&browser_version=102.0&resolution=1800x1014&speed=1&start=true&ref=netlify-source)

Submitted from [Netlify Deploy Preview #54](https://deploy-preview-54--2022-dcdw.netlify.app/)

**Comment by marcusrelacion** [comment]
Updated copy, but cards are still different heights. Will update the card so they're always the same height.
