### ISSUE TITLE
Update Years Text

### ISSUE THREAD

**Issue by silviascript** [AIGAdc/dcdesignweek.org-11ty#57]
![screenshot](https://netlify-cocoon.netlify.app/.netlify/functions/fetch?code=307&path=eyJzaXRlX2lkIjoiNjk1NmZkOGMtOWNkZS00YmQ1LWE0MTktZjI5ZDY0MGE5OTUyIiwiZGVwbG95X2lkIjoiNjJhZTAzNzAyZDFkMTIwMDA5NWM5ZDNmIiwiaWQiOiIxZGM2ZDk1YS1mNGViLTQyMzUtYjJkMS0zZTk3YzVjZDkzNzAifQ==)

### Description of issue
The second sentence should be updated to the following. "Checkout 2016, 2017, 2018 and 2019!". Add add without the comma. Updating from the original content.

```
Path:      /
Browser:   Chrome 102.0.0.0 on Mac OS 10.15.7
Viewport:  1800 x 1014 @2x
Language:  en-US
Cookies:   Enabled
```

[Open in BrowserStack](https://www.browserstack.com/user/try-live?url=https%3A%2F%2Fdeploy-preview-54--2022-dcdw.netlify.app%2F&os=OS%20X&os_version=Catalina&browser=Chrome&browser_version=102.0&resolution=1800x1014&speed=1&start=true&ref=netlify-source)

Submitted from [Netlify Deploy Preview #54](https://deploy-preview-54--2022-dcdw.netlify.app/)

**Comment by marcusrelacion** [comment]
Fixed
