### ISSUE TITLE
Accessibility statement content repeats

### ISSUE THREAD

**Issue by joshkimux** [AIGAdc/dcdesignweek.org-11ty#60]
Some of the content repeats itself (see screenshot), hopefully this is an easy fix 🤞 

<img width="1517" alt="Screen Shot 2022-07-07 at 11 51 58 AM" src="https://user-images.githubusercontent.com/14154792/177817370-c34917f9-d10c-463f-b17f-07101c4a5626.png">

**Comment by marcusrelacion** [comment]
@joshkimux thanks for the flag 😮‍💨. I'll dig into this, this evening!
